### ISSUE TITLE
BitCoin is unstoppable 😂

### ISSUE THREAD

**Issue by CySxL** [level3tjg/RedditFilter#11]
![image](https://github.com/level3tjg/RedditFilter/assets/15531137/2c4f91d4-1358-4449-b6b5-2295bd59ef70)

Tester on iOS 16.3 with Reddit v2024.10.1. RedditFilter v1.1.1

**Comment by level3tjg** [comment]
Fixed as of 1.1.3

**Comment by CySxL** [comment]
> Fixed as of 1.1.3

❤️❤️
