### ISSUE TITLE
Promoted content still showing up (for me)

### ISSUE THREAD

**Issue by Jazooxd** [level3tjg/RedditFilter#14]
I just install lates version of reddit (2024.17.0) and Filter (1.1.4) and still show promoted post... what i do wrong?

![promo-comment](https://github.com/level3tjg/RedditFilter/assets/166530795/42559c52-f87a-4e74-8903-241abcdfaf33)

![Promo](https://github.com/level3tjg/RedditFilter/assets/166530795/22394312-1336-495f-8144-741ba08724c3)

**Comment by Jazooxd** [comment]
> Do you have promoted posts switched off in the feed filter settings?

where is it? iam dont have it... in setting. i link here the my ipa of reddit can you please look at it and say if i inject wrong or what i do wrong? i have in setting only Clear local history and retry pending... [here](https://gofile.io/d/BV4N2n) is my ipa

**Comment by level3tjg** [comment]
The only ipas I'll provide support for are ones I've uploaded as GitHub releases. The ipa you posted doesn't have any tweaks injected into it at all.
