### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by AstudilloMarillo** [level3tjg/RedditFilter#15]
I keep getting the message: 'Something went wrong. Try again later.'
Just trying to log in with username / password.

**Comment by level3tjg** [comment]
Are you jailbroken or did you sideload the app?

**Comment by AstudilloMarillo** [comment]
> Are you jailbroken or did you sideload the app?

I sideloaded the app

**Comment by Fridodo** [comment]
same here sideloaded throug altstore and cant login

**Comment by level3tjg** [comment]
Will check this out soon, in the meantime you can log in by connecting another account (Google or Apple) and logging in through that account.

**Comment by level3tjg** [comment]
Fixed in [v2024.18.0-1.1.5](https://github.com/level3tjg/RedditFilter/releases/tag/v2024.18.0-1.1.5)

**Comment by level3tjg** [comment]
> While the 'Something went wrong. Try again later.' message is now gone, I still can't login. I enter my correct account information, but now I get the message 'Incorrect username or password' even though it is, in fact, correct. Tried with multiple accounts.

I'm not able to reproduce this at all, I tried multiple accounts as well. You're welcome to create a new issue, it may be helpful if other users are experiencing the same thing.

**Comment by AstudilloMarillo** [comment]
> I'm not able to reproduce this at all, I tried multiple accounts as well. You're welcome to create a new issue, it may be helpful if other users are experiencing the same thing.

I don't know why it didn't work before, I definitely checked that the login info was correct. I tried it now once again and now it did work. I finally managed to log in 🙂.
