### ISSUE TITLE
Logged out every day

### ISSUE THREAD

**Issue by PeiLin3717** [level3tjg/RedditFilter#16]
Hi, thanks for the app. I got logged out automatically every day. Can you please find out why it does that?

**Comment by PeiLin3717** [comment]
it would happen after I close the app and reopen it.

**Comment by level3tjg** [comment]
Could you try the [latest release](https://github.com/level3tjg/RedditFilter/releases/tag/v2024.18.0-1.1.5) and see if this issue still occurs?

**Comment by PeiLin3717** [comment]
Thank you very much! I just installed the latest version and it works!
