### ISSUE TITLE
Still see promoted content

### ISSUE THREAD

**Issue by Invisible40** [level3tjg/RedditFilter#18]
I just installed this via TrollStore, and I am still seeing promoted content unfortunately

**Comment by Skates1616** [comment]
How did you fix this?

**Comment by Invisible40** [comment]
For me, it was the direction of the toggles which confused me. If it is turned to the left (aka. NOT blue color), then it will not be shown. If it is turned to the right (aka. it IS blue), then it will be shown

**Comment by Invisible40** [comment]
![1C3D214E-2B8D-4898-9955-7FFB756F3083](https://github.com/level3tjg/RedditFilter/assets/8390311/749e3439-78f0-4fec-8b64-002f2ec5ed30)

These settings mean that promoted, recommended, and livestreams will not be shown.
