### ISSUE TITLE
Crashing with latest update

### ISSUE THREAD

**Issue by vghost01** [level3tjg/RedditFilter#19]
The latest update introduces at least 2 bugs that will crash reddit:

1. Going to notifications and hitting "mark all as read" crashes reddit.
2. Applying a removal reason as a moderator to a post/comment crashes reddit.

These issues are not present in v1.1.3 of the tweak.

**Comment by level3tjg** [comment]
I'm unable to reproduce, could you attach crash logs?

**Comment by vghost01** [comment]
Sure. crash1.txt is crash log when marking notifications as read:
[crash1.txt](https://github.com/user-attachments/files/15902949/crash1.txt)

crash2.txt is crash log when applying a removal reason as mod:
[crash2.txt](https://github.com/user-attachments/files/15902952/crash2.txt)

**Comment by level3tjg** [comment]
Thanks for the quick reply. Fixed in 3195f0911425d415db53e94be27ca0c3369a5a28
