### ISSUE TITLE
Reddit App Crash

### ISSUE THREAD

**Issue by aluxkusu** [level3tjg/RedditFilter#21]
Im using a 6th gen iPad7.5 iOS 17.3.1 and I have installed The app with Trollstore but it crashes when opened
This is the crash log
[Crashlog.txt](https://github.com/user-attachments/files/15936313/Crashlog.txt)

**Comment by level3tjg** [comment]
Trollstore doesn't support iOS 17.3.1, install with another sideloading tool (AltStore / SideStore is recommended)
