### ISSUE TITLE
can't log in (but i can on official reddit)

### ISSUE THREAD

**Issue by ComfortableMilk4454** [level3tjg/RedditFilter#26]
using https://github.com/level3tjg/RedditFilter/releases/download/v2024.26.0-1.1.6/RedditFilter_2024.26.0-1.1.6.ipa, tells me wrong password even though im filling it from 1password the exact same way i did on official reddit v2024.33.0 when i tested a minute ago. iOS 17.6.1, iPhone 13 mini. sideloaded iPA through maplesign.

**Comment by level3tjg** [comment]
duplicate of #20

**Comment by ComfortableMilk4454** [comment]
resolved itself, thanks
