### ISSUE TITLE
Awards & AutoMod detail text bug on iPad

### ISSUE THREAD

**Issue by BillyCurtis** [level3tjg/RedditFilter#3]
![2A0D80F6-F3A6-45AF-A485-CC1E5B532DFD](https://user-images.githubusercontent.com/38408756/206036354-f36bbe2a-183c-465e-aa97-9aeb964d71e1.jpeg)

Device: iPad Mini 6 
Reddit: v2022.44.0
Tweak: v1.0.9

**Comment by level3tjg** [comment]
Should be fixed in 925e005765775563b55879616993a0324a50c5d9, could you install v1.1 and confirm?

**Comment by BillyCurtis** [comment]
Yes it’s now fixed on v1.1
