### ISSUE TITLE
nsfw not working on ipad

### ISSUE THREAD

**Issue by juan9999** [level3tjg/RedditFilter#5]
thanks so much for this tweek!

auto display nsfw not working on ipad works great on iphone 

Also do you have a version of us for a browser or can you recommend one?

update: it seems that the ipa that i downloaded has other tweaks other than yours. not sure which ones. feel free to close

**Comment by level3tjg** [comment]
The NSFW filter is only meant to completely remove NSFW posts from feeds, leaving the toggle on does nothing. You can set preferences for NSFW posts in Reddit's section in the iOS settings app
