### ISSUE TITLE
Promoted content showing up in Popular and News feed

### ISSUE THREAD

**Issue by Exit24** [level3tjg/RedditFilter#6]
I updated to Reddit app version 2023.19.0 using RedditFilter 1.1.1. 

I see promoted content while in the Popular and News feed. I don’t see promoted content inside the Home or Latest feeds. 

Under Reddit settings —> feed filter, I’ve turned off the promoted filter.

**Comment by level3tjg** [comment]
Looks like they've switched to pure swift implementations for those feeds, may take a while to fix. For now I'd recommend downgrading the app to a version that works

**Comment by Exit24** [comment]
Ok, thanks.

**Comment by level3tjg** [comment]
Could you confirm that this is still an issue? I'm trying to reproduce again in v2023.19.0 but am unable to.

**Comment by yodaluca23** [comment]
> Could you confirm that this is still an issue? I'm trying to reproduce again in v2023.19.0 but am unable to.

Yea, it seems to be working again on Reddit version 2023.29.0 RedditFilter 1.1.1 Jailbroken 6S 14.4 OdessyRa1n, but I remember previously when I tried it on my jailed device it had worked for like a week before randomly not working... I don't know...

**Comment by Exit24** [comment]
> Could you confirm that this is still an issue? I'm trying to reproduce again in v2023.19.0 but am unable to.

Yes, I still get promoted content in the Popular and News feed in 2023.19.0 with RedditFilter 1.1.1 and the promoted content toggle off in the feed filter. 

I also get the same results using Reddit 2023.26.0 and 2023.29.0 with RedditFilter 1.1.1. 

I’m not jailbroken btw.

**Comment by brendonjkding** [comment]
It seems swift implementation is enabled only on iOS 15 and above.

**Comment by yodaluca23** [comment]
> It seems swift implementation is enabled only on iOS 15 and above.

That is very interesting... If this is so, then maybe the tweak could also spoof the iOS version to the app?

**Comment by asdfzxcvbn** [comment]
i can confirm that it works by using iGameGod's iGSpoof to spoof `ProductVersion` to `14.8` and `BuildVersion` to `18H17`, i just can't figure out how to turn this into a theos tweak

**Comment by asdfzxcvbn** [comment]
i figured it out! open source @ https://github.com/asdfzxcvbn/RedditOSVersionSpoof

tested and working on ios 16.2 :)

**Comment by DalphinLoser** [comment]
I want to add that even with the iOS 14 spoof this wasn't working for me on an iPhone 12 pro running iOS 16.6.1. I was able to get it working though by swapping the info.plist in the newest build for one from a build where the filtering works (V2023.14.0 for me). No idea why this worked but it did for me.

Still getting promoted content in news but at least the filters work everywhere else now.

**Comment by caafurcias42** [comment]
> I was able to get it working though by swapping the info.plist in the newest build for one from a build where the filtering works (V2023.14.0 for me)
> 
Can confirm this works for me with the latest version 2023.50, but now the icon is gone. Any fix?

**Comment by asdfzxcvbn** [comment]
> > I was able to get it working though by swapping the info.plist in the newest build for one from a build where the filtering works (V2023.14.0 for me)
> 
> Can confirm this works for me with the latest version 2023.50, but now the icon is gone. Any fix?

maybe the app is just checking the version? if so a fix could be implemented, i'll play around with it and see

as for the icon being gone, the old Info.plist probably just doesnt include the current icons

**Comment by caafurcias42** [comment]
>as for the icon being gone, the old Info.plist probably just doesnt include the current icons
>
I just had to re-sign the ipa with ESign using the icon from the last version. I made a fully functional ipa. Interestingly, TRENDING TODAY does not update anymore, and the ads on the NEWS section persist. Here you go: https://1drv.ms/u/s!AoHdRYpTugMoh_VsBxDud7u_QkzBfw

**Comment by CySxL** [comment]
That's so cool! Can you make a rootless build also? Not sure if it works with derootifier tho..

**Comment by level3tjg** [comment]
Just now seeing the recent replies here, makes sense that I haven't been unable to reproduce since I've been using an iOS 14 device. I have an iOS 16 device now so I should be able to actually figure out what's causing this issue

**Comment by CySxL** [comment]
> Just now seeing the recent replies here, makes sense that I haven't been able to reproduce since I've been using an iOS 14 device. I have an iOS 16 device now so I should be able to actually figure out what's causing this issue

Thank You @level3tjg ！！❤️  Always big fan of you!!

**Comment by level3tjg** [comment]
As I suspected Reddit has switched from using [Texture](https://github.com/texturegroup/texture) to their own internal Swift framework, [SliceKit](https://www.reddit.com/r/RedditEng/comments/v3hpns/the_slicekit_series_introducing_our_new_ios/), on iOS 15+. My solution for now will likely be to just force it to use Texture, same as the iOS 14 spoof is doing, until I figure out how the new framework works.

**Comment by level3tjg** [comment]
Finally found a way to properly hide ads without spoofing the iOS version by modifying responses from the Reddit api. I created a [pre-release](https://github.com/level3tjg/RedditFilter/releases/tag/v2024.17.0-1.1.4) with the changes, if someone could confirm it works I'll create an official release. This only affects the Home, News and Popular feeds, as far as I know all other feeds still use Texture.

**Comment by CySxL** [comment]
> Finally found a way to properly hide ads without spoofing the iOS version by modifying responses from the Reddit api. I created a [pre-release](https://github.com/level3tjg/RedditFilter/releases/tag/v2024.17.0-1.1.4) with the changes, if someone could confirm it works I'll create an official release. This only affects the Home, News and Popular feeds, as far as I know all other feeds still use Texture.

Heading to confirm.

**Comment by CySxL** [comment]
Tested on Reddit 2024.17.0, so far so good. No ads are shown.

**Comment by caafurcias42** [comment]
I’m happy to report that I didn’t see a single ad, the app never crashed and on top of that, these new versions of Reddit are extremely smooth and fast. I’m seriously considering jumping from Apollo finally. Excellent job with the mod.

**Comment by level3tjg** [comment]
Seems all is good then, new release is up now.
