### ISSUE TITLE
Promoted and recommended content now showing up in Home feed

### ISSUE THREAD

**Issue by DetachHead** [level3tjg/RedditFilter#8]
![image](https://github.com/level3tjg/RedditFilter/assets/57028336/365d5153-12e7-44bb-aa49-d7ab440a59d8)

![image](https://github.com/level3tjg/RedditFilter/assets/57028336/d32335bd-1041-41c2-88bd-56d5d5e9197d)

**Comment by level3tjg** [comment]
Fixed as of 1.1.3
